package ru.eda.plgn.bizgen.generators.impl

import ru.eda.plgn.bizgen.generators.Generator
import ru.eda.plgn.bizgen.generators.GeneratorResult

/**
 * Генератор стран.
 *
 * @author Dmitry_Emelyanenko
 */
class CountryGenerator : Generator<String> {
  override val uniqueDistance: Int = 5

  override fun generate(): GeneratorResult<String> =
    getCountryStructAsStr().let { (country, info) -> GeneratorResult(toClipboard = country.toString(), toEditor = info) }

  private companion object {

    fun getCountryStructAsStr(): Pair<Country, String> {
      return with(generateCountry()) {
        this to """
        /*
        code = $code
        name = $name
        engName = $engName
        alpha2Code = $alpha2Code
        alpha3Code = $alpha3Code
        */
      """.trimIndent()
      }
    }

    private fun generateCountry(): Country = countries.random()

    /**
     * Страна.
     *
     * @property code код страны (цифровой)
     * @property alpha2Code alpha2 код (2 символа)
     * @property alpha3Code alpha3 код (3 символа)
     * @property name название страны на русском в верхнем регистре
     * @property engName название страны на английском в верхнем регистре
     */
    data class Country(
      val code: String,
      val alpha2Code: String,
      val alpha3Code: String,
      val name: String,
      val engName: String,
    )

    val countries = listOf(
      Country("004", "AF", "AFG", "АФГАНИСТАН", "AFGHANISTAN"),
      Country("008", "AL", "ALB", "АЛБАНИЯ", "ALBANIA"),
      Country("010", "AQ", "ATA", "АНТАРКТИДА", "ANTARCTICA"),
      Country("012", "DZ", "DZA", "АЛЖИР", "ALGERIA"),
      Country("016", "AS", "ASM", "АМЕРИКАНСКОЕ САМОА", "AMERICAN SAMOA"),
      Country("020", "AD", "AND", "АНДОРРА", "ANDORRA"),
      Country("024", "AO", "AGO", "АНГОЛА", "ANGOLA"),
      Country("028", "AG", "ATG", "АНТИГУА И БАРБУДА", "ANTIGUA AND BARBUDA"),
      Country("031", "AZ", "AZE", "АЗЕРБАЙДЖАН", "AZERBAIJAN"),
      Country("032", "AR", "ARG", "АРГЕНТИНА", "ARGENTINA"),
      Country("036", "AU", "AUS", "АВСТРАЛИЯ", "AUSTRALIA"),
      Country("040", "AT", "AUT", "АВСТРИЯ", "AUSTRIA"),
      Country("044", "BS", "BHS", "БАГАМЫ", "BAHAMAS"),
      Country("048", "BH", "BHR", "БАХРЕЙН", "BAHRAIN"),
      Country("050", "BD", "BGD", "БАНГЛАДЕШ", "BANGLADESH"),
      Country("051", "AM", "ARM", "АРМЕНИЯ", "ARMENIA"),
      Country("052", "BB", "BRB", "БАРБАДОС", "BARBADOS"),
      Country("056", "BE", "BEL", "БЕЛЬГИЯ", "BELGIUM"),
      Country("060", "BM", "BMU", "БЕРМУДЫ", "BERMUDA"),
      Country("064", "BT", "BTN", "БУТАН", "BHUTAN"),
      Country("068", "BO", "BOL", "БОЛИВИЯ", "BOLIVIA"),
      Country("070", "BA", "BIH", "БОСНИЯ И ГЕРЦЕГОВИНА", "BOSNIA AND HERZEGOVINA"),
      Country("072", "BW", "BWA", "БОТСВАНА", "BOTSWANA"),
      Country("074", "BV", "BVT", "ОСТРОВ БУВЕ", "BOUVET ISLAND"),
      Country("076", "BR", "BRA", "БРАЗИЛИЯ", "BRAZIL"),
      Country("084", "BZ", "BLZ", "БЕЛИЗ", "BELIZE"),
      Country("086", "IO", "IOT", "БРИТАНСКАЯ ТЕРРИТОРИЯ В ИНДИЙСКОМ ОКЕАНЕ", "BRITISH INDIAN OCEAN TERRITORY"),
      Country("090", "SB", "SLB", "СОЛОМОНОВЫ ОСТРОВА", "SOLOMON ISLANDS"),
      Country("092", "VG", "VGB", "ВИРГИНСКИЕ ОСТРОВА (БРИТАНСКИЕ)", "VIRGIN ISLANDS (BRITISH)"),
      Country("096", "BN", "BRN", "БРУНЕЙ", "BRUNEI"),
      Country("100", "BG", "BGR", "БОЛГАРИЯ", "BULGARIA"),
      Country("104", "MM", "MMR", "МЬЯНМА", "MYANMAR"),
      Country("108", "BI", "BDI", "БУРУНДИ", "BURUNDI"),
      Country("112", "BY", "BLR", "БЕЛАРУСЬ", "BELARUS"),
      Country("116", "KH", "KHM", "КАМБОДЖА", "CAMBODIA"),
      Country("120", "CM", "CMR", "КАМЕРУН", "CAMEROON"),
      Country("124", "CA", "CAN", "КАНАДА", "CANADA"),
      Country("132", "CV", "CPV", "КАБО-ВЕРДЕ", "CABO VERDE"),
      Country("136", "KY", "CYM", "ОСТРОВА КАЙМАН", "CAYMAN ISLANDS"),
      Country("140", "CF", "CAF", "ЦЕНТРАЛЬНОАФРИКАНСКАЯ РЕСПУБЛИКА", "CENTRAL AFRICAN REPUBLIC"),
      Country("144", "LK", "LKA", "ШРИ-ЛАНКА", "SRI LANKA"),
      Country("148", "TD", "TCD", "ЧАД", "CHAD"),
      Country("152", "CL", "CHL", "ЧИЛИ", "CHILE"),
      Country("156", "CN", "CHN", "КИТАЙ", "CHINA"),
      Country("158", "TW", "TWN", "ТАЙВАНЬ", "TAIWAN"),
      Country("162", "CX", "CXR", "ОСТРОВ РОЖДЕСТВА", "CHRISTMAS ISLAND"),
      Country("166", "CC", "CCK", "КОКОСОВЫЕ (КИЛИНГ) ОСТРОВА", "COCOS (KEELING) ISLANDS"),
      Country("170", "CO", "COL", "КОЛУМБИЯ", "COLOMBIA"),
      Country("174", "KM", "COM", "КОМОРЫ", "COMOROS"),
      Country("175", "YT", "MYT", "МАЙОТТА", "MAYOTTE"),
      Country("178", "CG", "COG", "КОНГО", "CONGO"),
      Country("180", "CD", "COD", "ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА КОНГО", "DEMOCRATIC REPUBLIC OF THE CONGO"),
      Country("184", "CK", "COK", "ОСТРОВА КУКА", "COOK ISLANDS"),
      Country("188", "CR", "CRI", "КОСТА-РИКА", "COSTA RICA"),
      Country("191", "HR", "HRV", "ХОРВАТИЯ", "CROATIA"),
      Country("192", "CU", "CUB", "КУБА", "CUBA"),
      Country("196", "CY", "CYP", "КИПР", "CYPRUS"),
      Country("203", "CZ", "CZE", "ЧЕХИЯ", "CZECHIA"),
      Country("204", "BJ", "BEN", "БЕНИН", "BENIN"),
      Country("208", "DK", "DNK", "ДАНИЯ", "DENMARK"),
      Country("212", "DM", "DMA", "ДОМИНИКА", "DOMINICA"),
      Country("214", "DO", "DOM", "ДОМИНИКАНСКАЯ РЕСПУБЛИКА", "DOMINICAN REPUBLIC"),
      Country("218", "EC", "ECU", "ЭКВАДОР", "ECUADOR"),
      Country("222", "SV", "SLV", "САЛЬВАДОР", "EL SALVADOR"),
      Country("226", "GQ", "GNQ", "ЭКВАТОРИАЛЬНАЯ ГВИНЕЯ", "EQUATORIAL GUINEA"),
      Country("231", "ET", "ETH", "ЭФИОПИЯ", "ETHIOPIA"),
      Country("232", "ER", "ERI", "ЭРИТРЕЯ", "ERITREA"),
      Country("233", "EE", "EST", "ЭСТОНИЯ", "ESTONIA"),
      Country("234", "FO", "FRO", "ФАРЕРСКИЕ ОСТРОВА", "FAROE ISLANDS"),
      Country("238", "FK", "FLK", "ФОЛКЛЕНДСКИЕ ОСТРОВА", "FALKLAND ISLANDS"),
      Country("239", "GS", "SGS", "ЮЖНАЯ ГЕОРГИЯ И ЮЖНЫЕ САНДВИЧЕВЫ ОСТРОВА", "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"),
      Country("242", "FJ", "FJI", "ФИДЖИ", "FIJI"),
      Country("246", "FI", "FIN", "ФИНЛЯНДИЯ", "FINLAND"),
      Country("248", "AX", "ALA", "АЛАНДСКИЕ ОСТРОВА", "ALAND ISLANDS"),
      Country("250", "FR", "FRA", "ФРАНЦИЯ", "FRANCE"),
      Country("254", "GF", "GUF", "ФРАНЦУЗСКАЯ ГВИАНА", "FRENCH GUIANA"),
      Country("258", "PF", "PYF", "ФРАНЦУЗСКАЯ ПОЛИНЕЗИЯ", "FRENCH POLYNESIA"),
      Country("260", "TF", "ATF", "ФРАНЦУЗСКИЕ ЮЖНЫЕ ТЕРРИТОРИИ", "FRENCH SOUTHERN TERRITORIES"),
      Country("262", "DJ", "DJI", "ДЖИБУТИ", "DJIBOUTI"),
      Country("266", "GA", "GAB", "ГАБОН", "GABON"),
      Country("268", "GE", "GEO", "ГРУЗИЯ", "GEORGIA"),
      Country("270", "GM", "GMB", "ГАМБИЯ", "GAMBIA"),
      Country("275", "PS", "PSE", "ПАЛЕСТИНА", "PALESTINE"),
      Country("276", "DE", "DEU", "ГЕРМАНИЯ", "GERMANY"),
      Country("288", "GH", "GHA", "ГАНА", "GHANA"),
      Country("292", "GI", "GIB", "ГИБРАЛТАР", "GIBRALTAR"),
      Country("296", "KI", "KIR", "КИРИБАТИ", "KIRIBATI"),
      Country("300", "GR", "GRC", "ГРЕЦИЯ", "GREECE"),
      Country("304", "GL", "GRL", "ГРЕНЛАНДИЯ", "GREENLAND"),
      Country("308", "GD", "GRD", "ГРЕНАДА", "GRENADA"),
      Country("312", "GP", "GLP", "ГВАДЕЛУПА", "GUADELOUPE"),
      Country("316", "GU", "GUM", "ГУАМ", "GUAM"),
      Country("320", "GT", "GTM", "ГВАТЕМАЛА", "GUATEMALA"),
      Country("324", "GN", "GIN", "ГВИНЕЯ", "GUINEA"),
      Country("328", "GY", "GUY", "ГАЙАНА", "GUYANA"),
      Country("332", "HT", "HTI", "ГАИТИ", "HAITI"),
      Country("334", "HM", "HMD", "ОСТРОВ ХЕРД И ОСТРОВА МАКДОНАЛЬД", "HEARD ISLAND AND MCDONALD ISLANDS"),
      Country("336", "VA", "VAT", "ВАТИКАН", "VATICAN CITY"),
      Country("340", "HN", "HND", "ГОНДУРАС", "HONDURAS"),
      Country("344", "HK", "HKG", "ГОНКОНГ", "HONG KONG"),
      Country("348", "HU", "HUN", "ВЕНГРИЯ", "HUNGARY"),
      Country("352", "IS", "ISL", "ИСЛАНДИЯ", "ICELAND"),
      Country("356", "IN", "IND", "ИНДИЯ", "INDIA"),
      Country("360", "ID", "IDN", "ИНДОНЕЗИЯ", "INDONESIA"),
      Country("364", "IR", "IRN", "ИРАН", "IRAN"),
      Country("368", "IQ", "IRQ", "ИРАК", "IRAQ"),
      Country("372", "IE", "IRL", "ИРЛАНДИЯ", "IRELAND"),
      Country("376", "IL", "ISR", "ИЗРАИЛЬ", "ISRAEL"),
      Country("380", "IT", "ITA", "ИТАЛИЯ", "ITALY"),
      Country("384", "CI", "CIV", "КОТ-Д'ИВУАР", "COTE D'IVOIRE"),
      Country("388", "JM", "JAM", "ЯМАЙКА", "JAMAICA"),
      Country("392", "JP", "JPN", "ЯПОНИЯ", "JAPAN"),
      Country("398", "KZ", "KAZ", "КАЗАХСТАН", "KAZAKHSTAN"),
      Country("400", "JO", "JOR", "ИОРДАНИЯ", "JORDAN"),
      Country("404", "KE", "KEN", "КЕНИЯ", "KENYA"),
      Country("408", "KP", "PRK", "КОРЕЙСКАЯ НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА", "NORTH KOREA"),
      Country("410", "KR", "KOR", "КОРЕЯ", "SOUTH KOREA"),
      Country("414", "KW", "KWT", "КУВЕЙТ", "KUWAIT"),
      Country("417", "KG", "KGZ", "КЫРГЫЗСТАН", "KYRGYZSTAN"),
      Country("418", "LA", "LAO", "ЛАОС", "LAOS"),
      Country("422", "LB", "LBN", "ЛИВАН", "LEBANON"),
      Country("426", "LS", "LSO", "ЛЕСОТО", "LESOTHO"),
      Country("428", "LV", "LVA", "ЛАТВИЯ", "LATVIA"),
      Country("430", "LR", "LBR", "ЛИБЕРИЯ", "LIBERIA"),
      Country("434", "LY", "LBY", "ЛИВИЯ", "LIBYA"),
      Country("438", "LI", "LIE", "ЛИХТЕНШТЕЙН", "LIECHTENSTEIN"),
      Country("440", "LT", "LTU", "ЛИТВА", "LITHUANIA"),
      Country("442", "LU", "LUX", "ЛЮКСЕМБУРГ", "LUXEMBOURG"),
      Country("446", "MO", "MAC", "МАКАО", "MACAO"),
      Country("450", "MG", "MDG", "МАДАГАСКАР", "MADAGASCAR"),
      Country("454", "MW", "MWI", "МАЛАВИ", "MALAWI"),
      Country("458", "MY", "MYS", "МАЛАЙЗИЯ", "MALAYSIA"),
      Country("462", "MV", "MDV", "МАЛЬДИВЫ", "MALDIVES"),
      Country("466", "ML", "MLI", "МАЛИ", "MALI"),
      Country("470", "MT", "MLT", "МАЛЬТА", "MALTA"),
      Country("474", "MQ", "MTQ", "МАРТИНИКА", "MARTINIQUE"),
      Country("478", "MR", "MRT", "МАВРИТАНИЯ", "MAURITANIA"),
      Country("480", "MU", "MUS", "МАВРИКИЙ", "MAURITIUS"),
      Country("484", "MX", "MEX", "МЕКСИКА", "MEXICO"),
      Country("492", "MC", "MCO", "МОНАКО", "MONACO"),
      Country("496", "MN", "MNG", "МОНГОЛИЯ", "MONGOLIA"),
      Country("498", "MD", "MDA", "МОЛДОВА", "MOLDOVA"),
      Country("499", "ME", "MNE", "ЧЕРНОГОРИЯ", "MONTENEGRO"),
      Country("500", "MS", "MSR", "МОНТСЕРРАТ", "MONTSERRAT"),
      Country("504", "MA", "MAR", "МАРОККО", "MOROCCO"),
      Country("508", "MZ", "MOZ", "МОЗАМБИК", "MOZAMBIQUE"),
      Country("512", "OM", "OMN", "ОМАН", "OMAN"),
      Country("516", "NA", "NAM", "НАМИБИЯ", "NAMIBIA"),
      Country("520", "NR", "NRU", "НАУРУ", "NAURU"),
      Country("524", "NP", "NPL", "НЕПАЛ", "NEPAL"),
      Country("528", "NL", "NLD", "НИДЕРЛАНДЫ", "NETHERLANDS"),
      Country("531", "CW", "CUW", "КЮРАСАО", "CURACAO"),
      Country("533", "AW", "ABW", "АРУБА", "ARUBA"),
      Country("534", "SX", "SXM", "СЕН-МАРТЕН", "SINT MAARTEN"),
      Country("535", "BQ", "BES", "БОНЕЙР, СИНТ-ЭСТАТИУС И САБА", "BONAIRE, SINT EUSTATIUS AND SABA"),
      Country("540", "NC", "NCL", "НОВАЯ КАЛЕДОНИЯ", "NEW CALEDONIA"),
      Country("548", "VU", "VUT", "ВАНУАТУ", "VANUATU"),
      Country("554", "NZ", "NZL", "НОВАЯ ЗЕЛАНДИЯ", "NEW ZEALAND"),
      Country("558", "NI", "NIC", "НИКАРАГУА", "NICARAGUA"),
      Country("562", "NE", "NER", "НИГЕР", "NIGER"),
      Country("566", "NG", "NGA", "НИГЕРИЯ", "NIGERIA"),
      Country("570", "NU", "NIU", "НИУЭ", "NIUE"),
      Country("574", "NF", "NFK", "ОСТРОВ НОРФОЛК", "NORFOLK ISLAND"),
      Country("578", "NO", "NOR", "НОРВЕГИЯ", "NORWAY"),
      Country("580", "MP", "MNP", "СЕВЕРНЫЕ МАРИАНСКИЕ ОСТРОВА", "NORTHERN MARIANA ISLANDS"),
      Country("581", "UM", "UMI", "МАЛЫЕ ТИХООКЕАНСКИЕ ОСТРОВА США", "UNITED STATES MINOR OUTLYING ISLANDS"),
      Country("583", "FM", "FSM", "МИКРОНЕЗИЯ", "MICRONESIA"),
      Country("584", "MH", "MHL", "МАРШАЛЛОВЫ ОСТРОВА", "MARSHALL ISLANDS"),
      Country("585", "PW", "PLW", "ПАЛАУ", "PALAU"),
      Country("586", "PK", "PAK", "ПАКИСТАН", "PAKISTAN"),
      Country("591", "PA", "PAN", "ПАНАМА", "PANAMA"),
      Country("598", "PG", "PNG", "ПАПУА - НОВАЯ ГВИНЕЯ", "PAPUA NEW GUINEA"),
      Country("600", "PY", "PRY", "ПАРАГВАЙ", "PARAGUAY"),
      Country("604", "PE", "PER", "ПЕРУ", "PERU"),
      Country("608", "PH", "PHL", "ФИЛИППИНЫ", "PHILIPPINES"),
      Country("612", "PN", "PCN", "ПИТКЕРН", "PITCAIRN"),
      Country("616", "PL", "POL", "ПОЛЬША", "POLAND"),
      Country("620", "PT", "PRT", "ПОРТУГАЛИЯ", "PORTUGAL"),
      Country("624", "GW", "GNB", "ГВИНЕЯ-БИСАУ", "GUINEA-BISSAU"),
      Country("626", "TL", "TLS", "ТИМОР-ЛЕСТИ", "TIMOR-LESTE"),
      Country("630", "PR", "PRI", "ПУЭРТО-РИКО", "PUERTO RICO"),
      Country("634", "QA", "QAT", "КАТАР", "QATAR"),
      Country("638", "RE", "REU", "РЕЮНЬОН", "REUNION"),
      Country("642", "RO", "ROU", "РУМЫНИЯ", "ROMANIA"),
      Country("643", "RU", "RUS", "РОССИЯ", "RUSSIA"),
      Country("646", "RW", "RWA", "РУАНДА", "RWANDA"),
      Country("652", "BL", "BLM", "СЕН-БАРТЕЛЕМИ", "SAINT BARTHELEMY"),
      Country("654", "SH", "SHN", "ОСТРОВ СВЯТОЙ ЕЛЕНЫ", "SAINT HELENA"),
      Country("659", "KN", "KNA", "СЕНТ-КИТС И НЕВИС", "SAINT KITTS AND NEVIS"),
      Country("660", "AI", "AIA", "АНГИЛЬЯ", "ANGUILLA"),
      Country("662", "LC", "LCA", "СЕНТ-ЛЮСИЯ", "SAINT LUCIA"),
      Country("663", "MF", "MAF", "СЕН-МАРТЕН", "SAINT MARTIN"),
      Country("666", "PM", "SPM", "СЕН-ПЬЕР И МИКЕЛОН", "SAINT PIERRE AND MIQUELON"),
      Country("670", "VC", "VCT", "СЕНТ-ВИНСЕНТ И ГРЕНАДИНЫ", "SAINT VINCENT AND THE GRENADINES"),
      Country("674", "SM", "SMR", "САН-МАРИНО", "SAN MARINO"),
      Country("678", "ST", "STP", "САН-ТОМЕ И ПРИНСИПИ", "SAO TOME AND PRINCIPE"),
      Country("682", "SA", "SAU", "САУДОВСКАЯ АРАВИЯ", "SAUDI ARABIA"),
      Country("686", "SN", "SEN", "СЕНЕГАЛ", "SENEGAL"),
      Country("688", "RS", "SRB", "СЕРБИЯ", "SERBIA"),
      Country("690", "SC", "SYC", "СЕЙШЕЛЫ", "SEYCHELLES"),
      Country("694", "SL", "SLE", "СЬЕРРА-ЛЕОНЕ", "SIERRA LEONE"),
      Country("702", "SG", "SGP", "СИНГАПУР", "SINGAPORE"),
      Country("703", "SK", "SVK", "СЛОВАКИЯ", "SLOVAKIA"),
      Country("704", "VN", "VNM", "ВЬЕТНАМ", "VIETNAM"),
      Country("705", "SI", "SVN", "СЛОВЕНИЯ", "SLOVENIA"),
      Country("706", "SO", "SOM", "СОМАЛИ", "SOMALIA"),
      Country("710", "ZA", "ZAF", "ЮЖНАЯ АФРИКА", "SOUTH AFRICA"),
      Country("716", "ZW", "ZWE", "ЗИМБАБВЕ", "ZIMBABWE"),
      Country("724", "ES", "ESP", "ИСПАНИЯ", "SPAIN"),
      Country("728", "SS", "SSD", "ЮЖНЫЙ СУДАН", "SOUTH SUDAN"),
      Country("729", "SD", "SDN", "СУДАН", "SUDAN"),
      Country("732", "EH", "ESH", "ЗАПАДНАЯ САХАРА", "WESTERN SAHARA"),
      Country("740", "SR", "SUR", "СУРИНАМ", "SURINAME"),
      Country("744", "SJ", "SJM", "ШПИЦБЕРГЕН И ЯН-МАЙЕН", "SVALBARD AND JAN MAYEN"),
      Country("748", "SZ", "SWZ", "ЭСВАТИНИ", "ESWATINI"),
      Country("752", "SE", "SWE", "ШВЕЦИЯ", "SWEDEN"),
      Country("756", "CH", "CHE", "ШВЕЙЦАРИЯ", "SWITZERLAND"),
      Country("760", "SY", "SYR", "СИРИЯ", "SYRIA"),
      Country("762", "TJ", "TJK", "ТАДЖИКИСТАН", "TAJIKISTAN"),
      Country("764", "TH", "THA", "ТАИЛАНД", "THAILAND"),
      Country("768", "TG", "TGO", "ТОГО", "TOGO"),
      Country("772", "TK", "TKL", "ТОКЕЛАУ", "TOKELAU"),
      Country("776", "TO", "TON", "ТОНГА", "TONGA"),
      Country("780", "TT", "TTO", "ТРИНИДАД И ТОБАГО", "TRINIDAD AND TOBAGO"),
      Country("784", "AE", "ARE", "ОБЪЕДИНЕННЫЕ АРАБСКИЕ ЭМИРАТЫ", "UNITED ARAB EMIRATES"),
      Country("788", "TN", "TUN", "ТУНИС", "TUNISIA"),
      Country("792", "TR", "TUR", "ТУРЦИЯ", "TURKEY"),
      Country("795", "TM", "TKM", "ТУРКМЕНИСТАН", "TURKMENISTAN"),
      Country("796", "TC", "TCA", "ОСТРОВА ТЕРКС И КАЙКОС", "TURKS AND CAICOS ISLANDS"),
      Country("798", "TV", "TUV", "ТУВАЛУ", "TUVALU"),
      Country("800", "UG", "UGA", "УГАНДА", "UGANDA"),
      Country("804", "UA", "UKR", "УКРАИНА", "UKRAINE"),
      Country("807", "MK", "MKD", "СЕВЕРНАЯ МАКЕДОНИЯ", "NORTH MACEDONIA"),
      Country("818", "EG", "EGY", "ЕГИПЕТ", "EGYPT"),
      Country("831", "GG", "GGY", "ГЕРНСИ", "GUERNSEY"),
      Country("832", "JE", "JEY", "ДЖЕРСИ", "JERSEY"),
      Country("833", "IM", "IMN", "ОСТРОВ МЭН", "ISLE OF MAN"),
      Country("840", "US", "USA", "СОЕДИНЕННЫЕ ШТАТЫ АМЕРИКИ", "UNITED STATES"),
      Country("850", "VI", "VIR", "ВИРГИНСКИЕ ОСТРОВА (США)", "VIRGIN ISLANDS (U.S.)"),
      Country("854", "BF", "BFA", "БУРКИНА-ФАСО", "BURKINA FASO"),
      Country("858", "UY", "URY", "УРУГВАЙ", "URUGUAY"),
      Country("860", "UZ", "UZB", "УЗБЕКИСТАН", "UZBEKISTAN"),
      Country("876", "WF", "WLF", "УОЛЛИС И ФУТУНА", "WALLIS AND FUTUNA"),
      Country("882", "WS", "WSM", "САМОА", "SAMOA"),
      Country("887", "YE", "YEM", "ЙЕМЕН", "YEMEN"),
      Country("894", "ZM", "ZMB", "ЗАМБИЯ", "ZAMBIA")
    )
  }
}